print("python install <nama_paket>") 
print("untuk membuat data palsu (fake)")
print("pip uninstall <nama paket>") 
print("untuk menghapus nama paket")
print("pip install <nama paket> --upgrade") 
print("untuk mengupgrade versi paket")
print("pip list") 
print("untuk melihat daftar paket")
print("pip serach <kata kunci>") 
print("untuk mencari nama paket")
